basic.showString("Think of a number between 1 to 10")
basic.showString("Input your answer here")
input.buttonIsPressed(Button.A)
basic.showString("The answer was...")
basic.showNumber(randint(1, 10))
