basic.show_string("Think of a number between 1 to 10")
basic.show_string("Input your answer here")
input.button_is_pressed(Button.A)
basic.show_string("The answer was...")
basic.show_number(randint(1, 10))
